version: '3'
services:
  app:
    container_name: bandmentions-app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - bandmentions-postgres          
    networks:
      - bandmentions-network


  bandmentions-postgres:
    image: postgres:latest
    container_name: bandmentions-db-postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database-postgres:/var/lib/postgresql/data
    networks:
      - bandmentions-network
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - bandmentions-postgres
    ports:
      - "5050:80"
    networks:
      - bandmentions-network
    restart: unless-stopped

volumes:
  api:
  database-postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  bandmentions-network:
    driver: bridge